[
    {
        "content": "<p>I freshly installed 6.2 on my office computer running Rocky and tried to save dataset with FAKE doi, but got grayed out after clicking on save. Please see attached the payara log and <br>\n<a href=\"/user_uploads/53090/qtQtrO2kP4BdztCrHMZHh3UM/server.log\">server.log</a><br>\nhelp!</p>",
        "id": 438440374,
        "sender_full_name": "Hansen C.",
        "timestamp": 1715631424
    },
    {
        "content": "<p>Huh, we just got the same report here: Error when trying to create a new Dataset (NullPointerException) <a href=\"https://github.com/IQSS/dataverse/issues/10557\">#10557</a></p>",
        "id": 438440585,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1715631508
    },
    {
        "content": "<p>Thanks for pointing me to the post. I think the newer payara version is the problem. I will try with the recommended version.</p>",
        "id": 438441080,
        "sender_full_name": "Hansen C.",
        "timestamp": 1715631705
    },
    {
        "content": "<p>It looks like pidProvider is null here: <a href=\"https://github.com/IQSS/dataverse/blob/v6.2/src/main/java/edu/harvard/iq/dataverse/engine/command/impl/AbstractCreateDatasetCommand.java#L89\">https://github.com/IQSS/dataverse/blob/v6.2/src/main/java/edu/harvard/iq/dataverse/engine/command/impl/AbstractCreateDatasetCommand.java#L89</a></p>",
        "id": 438441479,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1715631861
    },
    {
        "content": "<p>You say you're using FAKE. Should work. Hmm.</p>",
        "id": 438441586,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1715631904
    },
    {
        "content": "<p>But yeah, I dunno about older Payara.</p>",
        "id": 438441614,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1715631918
    },
    {
        "content": "<p>You are right. It must be caused by something else. Installed the recommended version and had the same issue.</p>",
        "id": 438447466,
        "sender_full_name": "Hansen C.",
        "timestamp": 1715634070
    },
    {
        "content": "<p>That's... not great. Any tips on how to reproduce this? Sounds like it's a fresh install. Traditional install (not Docker). You're just following the Installation Guide and running the Python installer?</p>",
        "id": 438449193,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1715634723
    },
    {
        "content": "<p>Yes. It was a fresh traditional install following the guide. The production 6.2 upgraded from 6.0 does not have this problem.</p>",
        "id": 438449951,
        "sender_full_name": "Hansen C.",
        "timestamp": 1715634972
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"663833\">@Hansen C.</span> you're all set right? I'm looking at <a href=\"https://github.com/IQSS/dataverse/issues/10557#issuecomment-2110850169\">https://github.com/IQSS/dataverse/issues/10557#issuecomment-2110850169</a></p>",
        "id": 438774884,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1715770371
    },
    {
        "content": "<p>For the 6.2 release, I just re-uploaded dvinstall.zip to include a fix: <a href=\"https://github.com/IQSS/dataverse/pull/10563#issuecomment-2115977364\">https://github.com/IQSS/dataverse/pull/10563#issuecomment-2115977364</a></p>",
        "id": 439082999,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1715885888
    },
    {
        "content": "<p>Thank you so much for your help and updating the zip file! I am all set. Best, Hansen</p>",
        "id": 439085161,
        "sender_full_name": "Hansen C.",
        "timestamp": 1715886719
    },
    {
        "content": "<p><span class=\"user-mention silent\" data-user-id=\"598112\">Philip Durbin</span> has marked this topic as resolved.</p>",
        "id": 439098471,
        "sender_full_name": "Notification Bot",
        "timestamp": 1715892367
    }
]