[
    {
        "content": "<p>Good afternoon,</p>\n<p>We are having a problem in our installation 4.20 where we are able to communicate with Datacite to obtain the DOI but then when we want to publish we are unable to send it.</p>\n<p>The error we have in the log are the following:</p>\n<p>[2025-05-14T10:30:56.882+0100] [glassfish 4.1] [SEVERE] [] [edu.harvard.iq.dataverse.DatasetPage] [tid: _ThreadID=53 _ThreadName=jk-connector(3)] [timeMillis: 1747215056882] [levelValue: 1000] [[<br>\nÂ  This dataset may not be published due to an error when contacting the &lt;a href=<a href=\"http://status.datacite.org/\">http://status.datacite.org</a> target=\"_blank\"/&gt; DataCite &lt;/a&gt; Service. Please try again.]]</p>\n<p>And:</p>\n<p>Caused by: javax.net.ssl.SSLHandshakeException:<br>\nsun.security.validator.ValidatorException:<br>\nPKIX path building failed:<br>\nsun.security.provider.certpath.SunCertPathBuilderException:<br>\nunable to find valid certification path to requested target</p>\n<p>We check the connection to the Datacite server:</p>\n<p><a href=\"/user_uploads/53090/U0ldzTSbZyWH25fdRcqhrR8g/image.png\">image.png</a></p>\n<div class=\"message_inline_image\"><a href=\"/user_uploads/53090/U0ldzTSbZyWH25fdRcqhrR8g/image.png\" title=\"image.png\"><img data-original-content-type=\"image/png\" data-original-dimensions=\"886x456\" src=\"/user_uploads/thumbnail/53090/U0ldzTSbZyWH25fdRcqhrR8g/image.png/840x560.webp\"></a></div><p>Thanks for your help.</p>",
        "id": 518106626,
        "sender_full_name": "Filipe Freitas",
        "timestamp": 1747238791
    },
    {
        "content": "<p>Hmm, sounds similar to something <span class=\"user-mention\" data-user-id=\"903222\">@Yuyun Wirawati</span> reported here: <a href=\"https://groups.google.com/g/dataverse-community/c/xD1gfiD5H-U/m/56aSTXkFEgAJ\">https://groups.google.com/g/dataverse-community/c/xD1gfiD5H-U/m/56aSTXkFEgAJ</a></p>",
        "id": 518107040,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1747238920
    },
    {
        "content": "<p>We replaced cacerts.jks to the newer version from Payara 5.2022.5. This resolved the issue for us.</p>",
        "id": 518202316,
        "sender_full_name": "Yuyun Wirawati",
        "timestamp": 1747282145
    },
    {
        "content": "<p>Fantastic!</p>",
        "id": 518269153,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1747306674
    }
]