[
    {
        "content": "<p>Dear All, </p>\n<p>I have a bit of old deployment of DV. 5.5 instance, \"Docker compose deployment.\" <br>\nit was working as usual, while downloading some datasets using the API the system issued 500 internal error, then it stopped working, after a couple of reboots and a Payara domain restart it did not fire up, there are many errors in the log, could somebody tell me what to start wu=ith to trouble shoot that ?!<br>\n<a href=\"/user_uploads/53090/kBwj78jeOfb9zUeNANXXnh-8/server.log\">server.log</a></p>",
        "id": 423806502,
        "sender_full_name": "Hossam El-Zalabany",
        "timestamp": 1709122890
    },
    {
        "content": "<p>Hi! You're using <a href=\"https://github.com/IQSS/dataverse-docker\">https://github.com/IQSS/dataverse-docker</a> ?</p>",
        "id": 423806980,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1709123080
    },
    {
        "content": "<p>Is your PostgreSQL working? I'm seeing this <code>Caused by: org.postgresql.util.PSQLException: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.</code></p>",
        "id": 423807715,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1709123382
    }
]