[
    {
        "content": "<p>The following json file creates a dataset with no errors using \"curl\" API command:<br>\n<code>curl -H \"X-Dataverse-key:$API_TOKEN\" -X POST \"$SERVER_URL/api/dataverses/$PARENT/datasets\" --upload-file dataset-finch1.json -H 'Content-type:application/json</code></p>\n<p>but that same json file <code>dataset-finch1.json</code> gives a validation error in pyDataverse:</p>\n<blockquote>\n<p>jsonschema.exceptions.ValidationError: {'name': 'CC0 1.0', 'uri': '<a href=\"http://creativecommons.org/publicdomain/zero/1.0'}\">http://creativecommons.org/publicdomain/zero/1.0'}</a> is not of type 'string'</p>\n</blockquote>\n<blockquote>\n<p>Failed validating 'type' in schema['properties']['datasetVersion']['properties']['license']:<br>\n    {'$id': '#/properties/datasetVersion/properties/license',<br>\n     'type': 'string'}</p>\n</blockquote>\n<p>My file is attached:<br>\n<a href=\"/user_uploads/53090/nbFks0OaH9oLP9Ysd_Aq1OD3/dataset-finch1.json\">dataset-finch1.json</a></p>\n<p>What is missing to make the json validate in pyDataverse?</p>",
        "id": 399798357,
        "sender_full_name": "Sherry Lake",
        "timestamp": 1698870303
    },
    {
        "content": "<p>Hmm. What version of pyDataverse are you using?</p>",
        "id": 399803785,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1698872873
    },
    {
        "content": "<p>I'm using V0.3.1 - <a href=\"https://pydataverse.readthedocs.io/en/latest/index.html\">https://pydataverse.readthedocs.io/en/latest/index.html</a></p>\n<p>I can create a dataset  with pyDataverse if I leave out the license part, but then the license on my newly created dataset is \"Custom\", which I don't want.</p>",
        "id": 399805952,
        "sender_full_name": "Sherry Lake",
        "timestamp": 1698873989
    },
    {
        "content": "<p>I guess I'd suggest opening an issue at <a href=\"https://github.com/gdcc/pyDataverse/issues\">https://github.com/gdcc/pyDataverse/issues</a></p>",
        "id": 399812949,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1698877954
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"599826\">@Sherry Lake</span> there is a huge chance that the schemas in <a href=\"https://github.com/gdcc/pyDataverse/tree/master/src/pyDataverse/schemas/json\">https://github.com/gdcc/pyDataverse/tree/master/src/pyDataverse/schemas/json</a> are outdated. Please create an issue, that would help a lot tracking this!</p>",
        "id": 399927039,
        "sender_full_name": "Oliver Bertuch",
        "timestamp": 1698928893
    },
    {
        "content": "<p>On a related note: <span class=\"user-mention\" data-user-id=\"626369\">@Don Sizemore</span> <span class=\"user-mention\" data-user-id=\"599841\">@Jan Range</span> <span class=\"user-mention\" data-user-id=\"598112\">@Philip Durbin</span> (and to some degree me) are trying to get the release train rolling again for pyDataverse. Stay tuned!</p>",
        "id": 399927183,
        "sender_full_name": "Oliver Bertuch",
        "timestamp": 1698928938
    },
    {
        "content": "<p>Thanks, for the information. I will create a issue.</p>\n<p>Issue created: <a href=\"https://github.com/gdcc/pyDataverse/issues/161\">https://github.com/gdcc/pyDataverse/issues/161</a></p>",
        "id": 399928105,
        "sender_full_name": "Sherry Lake",
        "timestamp": 1698929275
    },
    {
        "content": "<p>Thanks, Sherry. <span class=\"user-mention\" data-user-id=\"599841\">@Jan Range</span> check this out ^^</p>",
        "id": 399935582,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1698931507
    },
    {
        "content": "<p>Hi <span class=\"user-mention\" data-user-id=\"599826\">@Sherry Lake</span>! This is related to a missing header in the POST request. There is a fix on a fork of mine:</p>\n<p><a href=\"https://github.com/JR-1991/pyDataverse\">https://github.com/JR-1991/pyDataverse</a></p>\n<p>Can you try it with this version? Maybe you need to uninstall <code>pyDataverse</code> first for the changes to come into effect.</p>",
        "id": 399936331,
        "sender_full_name": "Jan Range",
        "timestamp": 1698931724
    },
    {
        "content": "<p>Even with the validation errors, I still ran the create dataset  command -<code>resp = api.create_dataset(\"uvacs\", ds.json())</code></p>\n<p>Dataset was created, but with \"Custom terms\" - it ignored the license part (assuming because of the failed validation).</p>",
        "id": 399938778,
        "sender_full_name": "Sherry Lake",
        "timestamp": 1698932536
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"599841\">@Jan Range</span> I am not sure how to uninstall pyDataverse and test your version. I'm on a Mac. Any hints on how to do that? I can try later this afternoon (East Coast US).</p>",
        "id": 399938965,
        "sender_full_name": "Sherry Lake",
        "timestamp": 1698932599
    },
    {
        "content": "<p>Of course, here is the command to run:</p>\n<div class=\"codehilite\" data-code-language=\"Bash\"><pre><span></span><code>pip<span class=\"w\"> </span>uninstall<span class=\"w\"> </span>pyDataverse\npip<span class=\"w\"> </span>install<span class=\"w\"> </span>git+https://github.com/JR-1991/pyDataverse\n</code></pre></div>\n<p>If it doesn't work we may need to figure out where the issue is.</p>",
        "id": 399939441,
        "sender_full_name": "Jan Range",
        "timestamp": 1698932734
    },
    {
        "content": "<p>Unfortunately, I got the same error with your version <span class=\"user-mention\" data-user-id=\"599841\">@Jan Range</span> (see the install lines below) . Problem seems to be in this json schema:<br>\n<a href=\"http://url\">https://github.com/gdcc/pyDataverse/blob/master/src/pyDataverse/schemas/json/dataset_upload_default_schema.json</a></p>\n<p>I uninstalled pyDataverse - After uninstalling, I typed this <br>\n<code>pip install git+https://github.com/JR-1991/pyDataverse</code></p>\n<p>which gave me results:</p>\n<div class=\"codehilite\"><pre><span></span><code>Defaulting to user installation because normal site-packages is not writeable\nCollecting git+https://github.com/JR-1991/pyDataverse\n  Cloning https://github.com/JR-1991/pyDataverse to /private/var/folders/r6/84fn85zs085b3c5n5hcg59xm0000gq/T/pip-req-build-gpqbzqwo\n  Running command git clone --filter=blob:none --quiet https://github.com/JR-1991/pyDataverse /private/var/folders/r6/84fn85zs085b3c5n5hcg59xm0000gq/T/pip-req-build-gpqbzqwo\n  Resolved https://github.com/JR-1991/pyDataverse to commit 0fcfcd3fbc6bf1aec869899f715a51dca25e91be\n  Preparing metadata (setup.py) ... done\nRequirement already satisfied: requests&gt;=2.12.0 in /Users/sah/Library/Python/3.9/lib/python/site-packages (from pyDataverse==0.3.1) (2.31.0)\nRequirement already satisfied: jsonschema&gt;=3.2.0 in /Users/sah/Library/Python/3.9/lib/python/site-packages (from pyDataverse==0.3.1) (4.18.4)\nRequirement already satisfied: attrs&gt;=22.2.0 in /Users/sah/Library/Python/3.9/lib/python/site-packages (from jsonschema&gt;=3.2.0-&gt;pyDataverse==0.3.1) (23.1.0)\nRequirement already satisfied: jsonschema-specifications&gt;=2023.03.6 in /Users/sah/Library/Python/3.9/lib/python/site-packages (from jsonschema&gt;=3.2.0-&gt;pyDataverse==0.3.1) (2023.7.1)\nRequirement already satisfied: referencing&gt;=0.28.4 in /Users/sah/Library/Python/3.9/lib/python/site-packages (from jsonschema&gt;=3.2.0-&gt;pyDataverse==0.3.1) (0.30.0)\nRequirement already satisfied: rpds-py&gt;=0.7.1 in /Users/sah/Library/Python/3.9/lib/python/site-packages (from jsonschema&gt;=3.2.0-&gt;pyDataverse==0.3.1) (0.9.2)\nRequirement already satisfied: charset-normalizer&lt;4,&gt;=2 in /Users/sah/Library/Python/3.9/lib/python/site-packages (from requests&gt;=2.12.0-&gt;pyDataverse==0.3.1) (3.2.0)\nRequirement already satisfied: idna&lt;4,&gt;=2.5 in /Users/sah/Library/Python/3.9/lib/python/site-packages (from requests&gt;=2.12.0-&gt;pyDataverse==0.3.1) (3.4)\nRequirement already satisfied: urllib3&lt;3,&gt;=1.21.1 in /Users/sah/Library/Python/3.9/lib/python/site-packages (from requests&gt;=2.12.0-&gt;pyDataverse==0.3.1) (2.0.4)\nRequirement already satisfied: certifi&gt;=2017.4.17 in /Users/sah/Library/Python/3.9/lib/python/site-packages (from requests&gt;=2.12.0-&gt;pyDataverse==0.3.1) (2023.7.22)\nBuilding wheels for collected packages: pyDataverse\n  Building wheel for pyDataverse (setup.py) ... done\n  Created wheel for pyDataverse: filename=pyDataverse-0.3.1-py3-none-any.whl size=32602 sha256=c58d4c133d30bbe3c64b726d087de264ddf6da74e8dd2ec7a6318afc6a1d0f2d\n  Stored in directory: /private/var/folders/r6/84fn85zs085b3c5n5hcg59xm0000gq/T/pip-ephem-wheel-cache-yzpofxys/wheels/61/2a/0a/07fb58afbbadb2ed13b0efe12205b86aaff3841ac8792fb06d\nSuccessfully built pyDataverse\nInstalling collected packages: pyDataverse\nSuccessfully installed pyDataverse-0.3.1\n</code></pre></div>",
        "id": 400015058,
        "sender_full_name": "Sherry Lake",
        "timestamp": 1698957186
    },
    {
        "content": "<p>On a related note, there's a new JSON Schema for Dataverse datasets at <a href=\"https://github.com/IQSS/dataverse/issues/9463\">#9463</a> if you'd like to play with it.</p>",
        "id": 400015774,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1698957527
    }
]