[
    {
        "content": "<p>I saw this yesterday and just now. I'm not sure why it's happening but restarting Docker seems to fix it:</p>\n<p><code>[ERROR] DOCKER&gt; I/O Error [Unable to start container id [99031a6de676] : {\"message\":\"error while creating mount source path '/Users/pdurbin/github/iqss/dataverse/docker-dev-volumes/postgresql/data': mkdir /Users/pdurbin/github/iqss/dataverse/docker-dev-volumes: file exists\"} (Internal Server Error: 500)]</code></p>",
        "id": 385479509,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1692197074
    },
    {
        "content": "<p>I haven't seen this since. Resolving.</p>",
        "id": 389627506,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1694083986
    },
    {
        "content": "<p><span class=\"user-mention silent\" data-user-id=\"598112\">Philip Durbin</span> has marked this topic as resolved.</p>",
        "id": 389627516,
        "sender_full_name": "Notification Bot",
        "timestamp": 1694083992
    }
]